# ----
# Site

title: CloudHealth API Guide
description: The official API guide for the CloudHealth Platform.
# baseurl: ""
url: http://apidocs.cloudhealthtech.com
google_analytics_key:
permalink: pretty
repository: https://github.com/CloudHealth/cht_api_guide

collections:
  documentation:
    title: Getting Started
    position: 1
  account:
    title: AWS Accounts in CloudHealth
    position: 2
  sso:
    title: SSO Configuration
    position: 3
  perspectives:
    title: Perspectives
    position: 4
  reporting:
    title: Reporting
    position: 5
  asset:
    title: Assets
    position: 6
  metrics:
    title: Metrics
    position: 7
  tagging:
    title: Tagging
    position: 8
  organization:
    title: Organization
    position: 9
  partner:
    title: Partner
    position: 10
  assignment:
    title: Partner AWS Account Assignment
    position: 11
  price-book:
    title: Partner Custom Price Books
    position: 12
  billing-rules:
    title: Partner Billing Rules
    position: 13
  service-principal:
    title: Azure Service Principals
    position: 14
  azure-partner:
    title: Azure Partner
    position: 15
  azure-assignment:
    title: Partner Azure Account Assignment
    position: 16
  gcp-account:
    title: GCP Billing Accounts
    position: 17

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENSE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      type: "documentation"
    values:
      _hide_content: true
  -
    scope:
      type: "api"
    values:
      _hide_content: true

types:
  - get
  - put
  - delete
  - post
  - patch
  - example

languages:
  bash: Bash
  c: C
  css: CSS
  html: HTML
  java: Java
  javascript: JavaScript
  json: JSON
  php: PHP
  python: Python
  ruby: Ruby

_options:
  content_markdown:
    format: p h4 h5 h6
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    styles: /css/editor.css

# theme: jekyll-theme-cayman
